version: 2.1
executors:
  csunity-ci:
    docker:
      - image: lyrositor/csunity-ci:latest
        auth:
          username: lyrositor
          password: $DOCKERHUB_PASSWORD
jobs:
  build:
    executor: csunity-ci
    steps:
      - run:
          name: Running builds on Unity CI
          command: python3 /csunity-ci/build.py /csunity-ci/config.toml
      - run:
          name: Moving test files
          command: mkdir -p /csunity-ci-build/tests/ && mv /csunity-ci-build/csunity-tests.xml /csunity-ci-build/tests/
      - store_test_results:
          path: /csunity-ci-build/tests/
      - store_artifacts:
          path: /csunity-ci-build/artifacts/
          destination: /
      - persist_to_workspace:
          root: /csunity-ci-build/
          paths:
            - csunity-*
  publish:
    executor: csunity-ci
    steps:
      - attach_workspace:
          at: /csunity-ci-build/
      - run:
          name: Checking date since last password change
          command: test $(( ($(date -d "now" +%s) - $(date -d "2019-05-21" +%s)) / 86400 )) -lt 90
      - run:
          name: Pushing builds to distribution platforms
          command: python3 /csunity-ci/publish.py /csunity-ci/config.toml
      - store_artifacts:
          path: /csunity-ci-publish/artifacts/humble/
          destination: /humble/
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /release\/.*/
            tags:
              only: ci
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /release\/.*/